server:
  port: 8090
  servlet:
    context-path: /myproject
    session:
      timeout: 1800
  tomcat:
    max-threads: 100        # tomcat最大线程数，默认为200
    uri-encoding: UTF-8     # tomcat的URI编码

logging:
  level: 
    root: INFO
    org:
      hibernate:
        sql: DEBUG
    druid:
      sql:
        DataSource: DEBUG
        Connection: DEBUG
        Statement: DEBUG
        #ResultSet: DEBUG
  #path: D:\workspace\log
  #file: SpringBoot.log
  #com.hhf.learn.config: classpath:logback.xml

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #指定时间格式
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password: 
    timeout: 10000  #redis操作的超时时间
    jedis:
      pool:
       maxActive: 5000 #最大连接数
       maxIdle: 30 #最大空闲连接数
       minIdle: 5 #最小空闲连接数
       maxWait: 3000  #获取连接最大等待时间 ms  #default -1

  #rabbitmq相关配置
  rabbitmq:
      host: 127.0.0.1
      port: 5672
  #    addresses: 10.196.20.63:5672,10.196.20.64:5672,10.196.20.65:5672  #使用集群时用adresses,如果有F5或HAProxy负载均衡，把负载ip写在第一个
      username: guest
      password: guest
      virtual-host: /
      publisher-confirms: true  #是否支持消息处理完毕确认时回调处理，如果要进行消息回调，则这里必须要设置为true，消息发送方需要实现RabbitTemplate.ConfirmCallback
      publisher-returns: true #消息未正确发送到exchage，对应的处理类需要实现RabbitTemplate.ReturnCallback
      requested-heartbeat: 10s  #连接的心跳超时时间，0为不指定.
      connection-timeout: 60s #连接超时时间，0表示一直等待
      listener:
        simple:
          auto-startup: true #是否在启动时就启动mq，默认: true
          acknowledge-mode: manual #auto为自动判断在消费者处理完后将消息从队列移除：正常返回则从队列移除，异常则不移除。
          concurrency: 3 #指定最小的消费者数量.
          max-concurrency: 10 #消费者最大线程数
          prefetch: 1 #指定消费者一次能处理多少个消息，如果有事务的话，必须大于等于transaction数量.
          transaction-size: 1 #指定消费者一个事务处理的消息数量，最好是小于等于prefetch的数量.
          retry:
            enabled: true
            max-attempts: 5
            initial-interval: 5s
            max-interval: 300s
      cache:
        connection:
          mode: connection  #缓存连接模式，channle表示使用一个连接来支持多个通道，connection表示每次使用,rabbitmq使用集群时，应该使用connection模式
          size: 50 #缓存的连接数，只有在连接缓存mode为connection才使用
        channel: #channel为一个虚拟的connection，不同事务使用
          checkout-timeout: 0s #channel满的情况，等待一个channel的等待时间
          size: 100  #缓存的通道的个数，超出个数时，触发checkout-timeout机制

  mvc:
    static-path-pattern: /**     # 静态文件请求匹配方式
  thymeleaf:
    mode: HTML                   #spring boot 2.x  参数变化
    encoding: UTF-8
#  redis:
#    database: 0
#    pool:
#      maxActive: 5000
#      maxWait: 3000
#      maxIdle: 30
#      minIdle: 5
#    timeout: 1000
#    #redis cluster com.hhf.learn.config
#    password: 5tgb7ygv
#    cluster.nodes: 10.186.125.235:7380,10.186.125.235:7381,10.186.125.235:7382,10.186.125.162:7380,10.186.125.162:7381,10.186.125.162:7382
#    cluster.max-redirects: 6

  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #&nullCatalogMeansCurrent=true    mysql8 工作流自动建表
    url: jdbc:mysql://localhost:3306/flowable?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: root
#    password: ${spring.datasource.druid.decrypt.password}  #密码使用阿里的加密机制
#    druid: #druid相关配置
#      initialSize: 5  # 初始化大小
#      minIdle: 5  # 最小连接数
#      maxActive: 200 # 最大连接数
#      maxWait: 60000 # 配置获取连接等待超时的时间
#      timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      minEvictableIdleTimeMillis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒
#      validationQuery: SELECT 1 FROM DUAL #验证连接是否有效的sql
#      testWhileIdle: true
#      testOnBorrow: false #获取连接时先验证连接是否有效
#      testOnReturn: false #归还连接时先验证连接是否有效
#      poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
#      maxPoolPreparedStatementPerConnectionSize: 20 # 打开PSCache，并且指定每个连接上PSCache的大小
#      filters: com.hhf.learn.config,stat,slf4j  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      decrypt: #自定义的配置文件 druid 加密密码使用的公钥
#        publickey: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIduifpg/5512kcZHxoCNc7RIGGNPYy79bc1DQyBJ0RTahXM/mKc6d4Krp+myMfAws0GKEYdIvyzOIOoiN0r/4sCAwEAAQ=="
#        password: "NyCbtcwLqJf/gmnrDIgsnZa92naqHYr7Ce4eY3+cKRpmBsP6rcA0Sg8kqa5J3UeD9IIG4SbHIL3JOaRyHwwAUw=="
#      connectionProperties: druid.log.stmt.executableSql=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;com.hhf.learn.config.decrypt=true;com.hhf.learn.config.decrypt.key=${spring.datasource.druid.decrypt.publickey} # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      useGlobalDataSourceStat: false # 合并多个DruidDataSource的监控数据
      
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      # 新特性
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # quartz任务配置   quartz通过 StdJDBCDelegate 这个类操作数据库  数据库表名是根据封装的这个类中的sql语句建立的
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true                                # 打开集群配置
            clusterCheckinInterval: 10000                    # 设置集群检查间隔20s
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

#mybatis-plus 配置，参考官方文档http://mp.baomidou.com
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  typeAliasesPackage: com.fndsoft.**.entity,com.fndsoft.**.eo,com.cpic.**.entity,com.cpic.**.eo  #类型别名扫描路径，多个package用逗号或者分号分隔
  global-config:
    # 数据库相关配置
    db-config:
      db-type: mysql  #数据库类型
      id-type: id_worker  #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      field-strategy: not_empty  #字段策略,新增和更新时用来动态判断是否处理空值。 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      column-underline: true  #驼峰下划线转换
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
    #刷新mapper 调试神器
    refresh: true #该配置不建议在生产环境打开
    # 原生配置
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    local-cache-scope: statement #1级缓存级别设置，默认为session级别
    cache-enabled: false #禁用二级缓存
    jdbc-type-for-null: 'null'  #配置JdbcTypeForNull, oracle数据库必须配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
